endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true

management:
  security:
    enabled: false

---
spring:
  profiles: consul-provider1
  application:
    name: consul-provider1

server:
  port: 8201

---
spring:
  profiles: consul-provider2
  application:
    name: consul-provider2

server:
  port: 8202

---
spring:
  profiles: consul-consumer
  application:
    name: consul-consumer
  cloud:
    consul:
      discovery:
        register: false
server:
  port: 9101